name: build push and deploy image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE}}

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code
  
jobs:
  build:
    runs-on: ubuntu-latest # github runner
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: AWS creds configs
        uses: aws-actions/configure-aws-credentials@V2
        with:
          role-to-assume: ${{ env.AWS_ROLE}}     # OIDC
          aws-region: ${{ env.AWS_REGION}}
 
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: ecr-login

