name: build push and deploy image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }}
  ECR_REPO_NAME: dev
  IMAGE_TAG: ${{ github.run_number }}


permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code
  
jobs:
  build:
    runs-on: ubuntu-latest # github runner
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: AWS creds configs
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          role-to-assume: ${{ env.AWS_ROLE }}     # OIDC
          aws-region: ${{ env.AWS_REGION }}
 
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: ecr-login

      - name: Build Tag and Push image
        id: build-and-push
        run: |
          docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}
          



